# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0006_auto_20160723_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='sexuality',
        ),
    ]
