# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0008_auto_20160723_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='portrait',
            field=models.ImageField(height_field=200, null=True, upload_to='/localStorage/portrait', width_field=200),
        ),
    ]
