# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0011_auto_20160724_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
