# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0013_auto_20160724_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='photo',
            field=models.ImageField(null=True, upload_to='portrait'),
        ),
    ]
