# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0014_auto_20160724_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='photo',
            field=models.ImageField(null=True, upload_to='studentforum/portrait'),
        ),
    ]
