# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0020_auto_20160725_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='photo',
            field=models.ImageField(null=True, upload_to='studentforum/res/photos'),
        ),
    ]
