# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0028_auto_20160725_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='url_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='url_width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
