# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0029_auto_20160725_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='url_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='url_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='portrait',
            field=models.ImageField(height_field='url_height', null=True, upload_to='studentforum/portraits', width_field='url_width'),
        ),
    ]
