# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0030_auto_20160725_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForWidgetTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name=' 内容')),
                ('title', models.CharField(default=' test', max_length=100)),
            ],
        ),
    ]
