# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0031_forwidgettest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='studentforum/files')),
                ('title', models.CharField(default=' test', max_length=100)),
            ],
        ),
    ]
