# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0009_auto_20160725_1600'),
        ('studentforum', '0031_forwidgettest'),
    ]

    operations = [
    ]
