# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0032_testfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(null=True, upload_to='studentforum/attachments'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(height_field='url_height', null=True, upload_to='studentforum/photos', width_field='url_width'),
        ),
        migrations.AddField(
            model_name='post',
            name='url_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='url_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='attachment',
            field=models.FileField(null=True, upload_to='studentforum/attachments'),
        ),
        migrations.AddField(
            model_name='reply',
            name='photo',
            field=models.ImageField(height_field='url_height', null=True, upload_to='studentforum/photos', width_field='url_width'),
        ),
        migrations.AddField(
            model_name='reply',
            name='url_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='url_width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
