# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0032_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='collectCls',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='collectClsNum',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='collectPst',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='collectPstNum',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='fansNum',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='followNum',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='manageType',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='pstNum',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='score',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ofColumn',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ofTopic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='supportNum',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='supportNum',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
