# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0033_auto_20160726_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('pstNum', models.IntegerField(default=0)),
                ('collectNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('userFromID', models.IntegerField(default=0)),
                ('userToID', models.IntegerField(default=0)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReplytoReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(null=True, verbose_name='楼中楼回帖')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('topicType', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('pstNum', models.IntegerField(default=0)),
                ('heat', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='collectClsNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='collectPst',
            field=models.ManyToManyField(to='studentforum.Post'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='collectPstNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='fansNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='follow',
            field=models.ManyToManyField(to='studentforum.MyUser'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='followNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='manageType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='pstNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='collectNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='supportNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='supportNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replytoreply',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentforum.Reply'),
        ),
        migrations.AddField(
            model_name='replytoreply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentforum.MyUser'),
        ),
        migrations.AddField(
            model_name='column',
            name='manager',
            field=models.ManyToManyField(to='studentforum.MyUser'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='collectCls',
            field=models.ManyToManyField(to='studentforum.Column'),
        ),
        migrations.AddField(
            model_name='post',
            name='ofColumn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentforum.Column'),
        ),
        migrations.AddField(
            model_name='post',
            name='ofTopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentforum.Topic'),
        ),
    ]
