# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0034_auto_20160726_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='type',
            new_name='topicType',
        ),
    ]
