# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0035_auto_20160726_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForWidgetTest',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
