# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0035_post_latestupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='likePst',
            field=models.ManyToManyField(related_name='likepersons', to='studentforum.Post'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='likeRst',
            field=models.ManyToManyField(related_name='likepersonlist', to='studentforum.Reply'),
        ),
        migrations.AddField(
            model_name='post',
            name='ischecked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isreported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='ischecked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='isreported',
            field=models.BooleanField(default=False),
        ),
    ]
