# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0036_auto_20160726_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='collectCls',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='collectClsNum',
        ),
    ]
