# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0036_auto_20160727_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTotal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstReportTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='reportPst',
            field=models.ManyToManyField(related_name='reportposts', to='studentforum.Post'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='reportRst',
            field=models.ManyToManyField(related_name='reportreplies', to='studentforum.Reply'),
        ),
        migrations.AddField(
            model_name='post',
            name='reportNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='reportNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posttotal',
            name='forpost',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentforum.Post'),
        ),
        migrations.AddField(
            model_name='posttotal',
            name='forreply',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentforum.Reply'),
        ),
    ]
