# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0037_auto_20160726_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True, verbose_name=' 内容（内容中插入#相关话题#可以将贴子与话题关联起来）'),
        ),
    ]
