# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0037_auto_20160727_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttotal',
            name='forreplytoreply',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentforum.ReplytoReply'),
        ),
        migrations.AddField(
            model_name='posttotal',
            name='publishTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='posttotal',
            name='reportNum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posttotal',
            name='type1',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
