# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0038_auto_20160727_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='reportRpytoRpy',
            field=models.ManyToManyField(related_name='reportreptorep', to='studentforum.ReplytoReply'),
        ),
    ]
