# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0038_auto_20160727_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='collectPst',
            field=models.ManyToManyField(null=True, to='studentforum.Post'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='follow',
            field=models.ManyToManyField(null=True, to='studentforum.MyUser'),
        ),
    ]
