# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0039_myuser_reportrpytorpy'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttotal',
            name='ischecked',
            field=models.BooleanField(default=False),
        ),
    ]
