# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0040_auto_20160727_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latestupdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
