# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0040_posttotal_ischecked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='userFromID',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='userToID',
        ),
        migrations.AddField(
            model_name='letter',
            name='userFrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverse_from', to='studentforum.MyUser'),
        ),
        migrations.AddField(
            model_name='letter',
            name='userTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverse_to', to='studentforum.MyUser'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=models.TextField(max_length=20, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True, verbose_name=' 内容（内容中插入#相关话题#可以将贴子与话题关联起来）'),
        ),
    ]
