# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0041_auto_20160728_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='isforbidden',
            field=models.BooleanField(default=False),
        ),
    ]
