# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0041_post_latestupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=models.TextField(max_length=500, verbose_name='内容'),
        ),
    ]
