# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0042_auto_20160728_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
