# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentforum', '0043_myuser_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isforbidden',
            field=models.BooleanField(default=False),
        ),
    ]
